### ISSUE TITLE
Auto update not so awesome on Ubuntu 20.04

### ISSUE THREAD

**Issue by njames** [beyondcode/tinkerwell-community#314]
At new release I get the message about a new release and that it will happen on restart but it doesn't. 

So each time I start tinkerwell it gives the same message until I manually download from your site. 

:) 

Have a great day

**Comment by singularo** [comment]
Had same with 2.8.1 (I think), manually downloaded 2.10.1 today, so we'll see next upgrade I guess.

**Comment by sschlein** [comment]
@singularo are you on Linux, too? Which version?

It seems that we have fixed the updater on Mac OS and Windows but Linux still has issues :(

**Comment by singularo** [comment]
Same version - Ubuntu 20.04:
```
% lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
% uname -a  
Linux t580 5.6.15-050615-generic #202005271638 SMP Wed May 27 16:42:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by njames** [comment]
for reference 
```
(base) 10:35:46 ~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by gpressutto5** [comment]
I thought it was only happening on docker beta releases (https://github.com/beyondcode/tinkerwell-community/issues/279#issuecomment-717524486).

```
$ lsb_release -a
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	20.1.2
Codename:	Mikah
```

**Comment by sschlein** [comment]
We are still using the standard Electron auto updater and we can't come up with a reason why it doesn't work for some folks.

Do other Electron apps update as normal are get installed in the same way than Tinkerwell does? Slack and VSCode might be some, there are likely others.

**Comment by hcancelik** [comment]
> We are still using the standard Electron auto updater and we can't come up with a reason why it doesn't work for some folks.
> 
> Do other Electron apps update as normal are get installed in the same way than Tinkerwell does? Slack and VSCode might be some, there are likely others.

I also have HELO app and that one updates without any problems. 

I'm on a Mac and this has been an issue since version 2.4.5 (see https://github.com/beyondcode/tinkerwell-community/issues/147)

**Comment by hcancelik** [comment]
Very interestingly just now, I've deleted `~/Library/Caches/de.beyondco.tinkerwell.ShipIt/` folder. I open the app and restarted after getting the update notification. Now it's updated 🎉

**Comment by njames** [comment]
Just updated to 2.12.x (was just released) 
I still found the update was download from beyond code, uninstall existing version and install new version and still no release notes at https://beyondco.de/docs/tinkerwell/releases/2-12-?

I still get the new version updated but maybe because I have installed it as a AppImage with an app that makes that simple that makes it hard to update?

May i mention snap's again? https://github.com/beyondcode/tinkerwell-community/issues/287

Happy to help provide any info that will help you with this or have the discussion about setup etc

**Comment by njames** [comment]
This *seems* to have been fixed. The last time I updated manually was above to 2.12.0 and I now notice that I am on 2.12.1 so the something magical seems to be working. 

:+1:

**Comment by cbaconnier** [comment]
> This _seems_ to have been fixed. The last time I updated manually was above to 2.12.0 and I now notice that I am on 2.12.1 so the something magical seems to be working.

I don't remember if I have updated manually to version 2.12.1 or if it did auto-update. But the issue is still there when trying to  update from 2.12.1 to 2.13

_(The issue is also present in HELO)_

**Comment by njames** [comment]
ditto @cbaconnier The update to 2.13.0 is just telling me to restart each time I restart. 

Back to the download manually. 

Mac people are happy though :)

**Comment by cbaconnier** [comment]
This is what happens when I run from the console. Hope this helps!

> 08:41:53.189 › Checking for update
> 08:41:53.497 › Found version 2.13.0 (url: Tinkerwell-2.13.0.AppImage)
> 08:41:53.499 › Downloading update from Tinkerwell-2.13.0.AppImage
> 08:41:53.503 › updater cache dir: /home/clement/.cache/tinkerwell-updater
> 08:41:53.865 › Update has already been downloaded to /home/clement/.cache/tinkerwell-updater/pending/Tinkerwell-2.13.0.AppImage).
> 08:42:30.104 › Auto install update on quit
> 08:42:30.105 › Install: isSilent: true, isForceRunAfter: false
> 08:42:30.107 › Error: Error: ENOSYS: function not implemented, unlink '/run/user/1000/appimagelauncherfs/0000.AppImage'
>     at unlinkSync (fs.js:976:3)
>     at p.doInstall (/tmp/.mount_TinkerA47Gcm/resources/app.asar/background.js:2:1198654)
>     at p.install (/tmp/.mount_TinkerA47Gcm/resources/app.asar/background.js:2:1200163)
>     at /tmp/.mount_TinkerA47Gcm/resources/app.asar/background.js:2:1200598
>     at App.<anonymous> (/tmp/.mount_TinkerA47Gcm/resources/app.asar/background.js:2:4244265)
>     at Object.onceWrapper (events.js:291:20)
>     at App.emit (events.js:208:15)
>     at App.EventEmitter.emit (domain.js:476:20)
>     at App.t.emit (/tmp/.mount_TinkerA47Gcm/resources/app.asar/background.js:2:4716255)
>     at App.topLevelDomainCallback (domain.js:131:23)

**Comment by ModestasV** [comment]
I'm having the same issue, but for me, it's with both Tinkerwell and HELO.

The problem occurs as follows:
1. Fresh ubuntu 20.04 installation
2. Download tinkerwell/HELO
3. Allow the app image to be executed
4. When the update is prompted - nothing happens if you close it or not.

I had to go and manually download them each time. 

ps. Using JetBrains toolbox which is via AppImage too - works fine

**Comment by mechelon** [comment]
Can anybody tell if this issue still occurs in the latest version?

**Comment by cbaconnier** [comment]
It worked for me! Thanks for your work on this :partying_face:
