### ISSUE TITLE
ctr+shift+r command not working on Linux (ubuntu 18.04 & 20.04)

### ISSUE THREAD

**Issue by allandereal** [beyondcode/tinkerwell-community#455]
This has been tested on both ubuntu 18.04 and 20.04.  
Nothing happens when I highlight a query line for example `User::first();` and press `ctr+shift+r` .

**Comment by bognerf** [comment]
Same here... **Query inspection** does not work at all.

**Comment by mpociot** [comment]
I've now added the "Run Query Inspection" entry to the main menu, so this should be fixed in the next version 👍

**Comment by allandereal** [comment]
The Menu command works but the shortcut still doesn't. @mpociot i think this issue should stay open untill the shortcut is fixed.
